# Generated by Django 4.2.11 on 2024-03-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unmute_app', '0002_accesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='user_id',
        ),
    ]
